baseurl = "https://jmarriott.com"
title = "jmarriott.com"
theme = ["hugo-coder", "jmcustom"]
languagecode = "en"
defaultcontentlanguage = "en"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "jmarriott"

[params]
    author = "Jameson Marriott"
    info = "Quality Control Manager"
    description = "Jameson Marriott's personal website"
    keywords = "blog,quality,personal,rstats"
    avatarurl = "images/jameson_bw.jpg"

    favicon_32 = "images/favicon32.png"
    favicon_16 = "images/favicon16.png"

    footercontent = "#rstats"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    
    #custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/jameson-marriott/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/jameson-marriott/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab fa-2x"
#    weight = 3
#    url = "https://gitlab.com/johndoe/"
#[/[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter fa-2x"
#    weight = 3
#    url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Christmas"
    weight = 3
    url  = "/christmas/"