[[redirects]]
  from = "/WCQI"
  to = "https://jameson-marriott.shinyapps.io/WCQI-2022"
  status = 301
  force = false
  
  [[redirects]]
  from = "/wcqi"
  to = "https://jameson-marriott.shinyapps.io/WCQI-2022"
  status = 301
  force = false